from __future__ import annotations

from app.models import DocumentRole, MeasureLifecycleStatus, RequirementMode, SurveyModule


def doc(
    url: str,
    title: str,
    role: str,
    lifecycle_status: str,
    relationship_type: str,
    summary: str,
) -> dict:
    return {
        'url': url,
        'title': title,
        'role': role,
        'lifecycle_status': lifecycle_status,
        'relationship_type': relationship_type,
        'summary': summary,
    }


def req(
    fact_key: str,
    requirement_mode: str,
    expected_values: list[str] | None = None,
    notes: str | None = None,
) -> dict:
    return {
        'fact_key': fact_key,
        'requirement_mode': requirement_mode,
        'expected_values': expected_values,
        'notes': notes,
    }


SOURCE_REGISTRY = [
    {
        'domain': 'normattiva.it',
        'name': 'Normattiva',
        'source_type': 'website',
        'authority_level': 'tier_1',
        'crawl_method': 'html',
        'crawl_frequency': 'weekly',
        'trust_level': 'high',
        'region': 'Italy',
    },
    {
        'domain': 'gazzettaufficiale.it',
        'name': 'Gazzetta Ufficiale',
        'source_type': 'website',
        'authority_level': 'tier_1',
        'crawl_method': 'html',
        'crawl_frequency': 'weekly',
        'trust_level': 'high',
        'region': 'Italy',
    },
    {
        'domain': 'invitalia.it',
        'name': 'Invitalia',
        'source_type': 'website',
        'authority_level': 'tier_1',
        'crawl_method': 'html',
        'crawl_frequency': 'daily',
        'trust_level': 'high',
        'region': 'Italy',
    },
    {
        'domain': 'mimit.gov.it',
        'name': 'Ministero delle Imprese e del Made in Italy',
        'source_type': 'website',
        'authority_level': 'tier_1',
        'crawl_method': 'html',
        'crawl_frequency': 'daily',
        'trust_level': 'high',
        'region': 'Italy',
    },
    {
        'domain': 'inps.it',
        'name': 'INPS',
        'source_type': 'website',
        'authority_level': 'tier_1',
        'crawl_method': 'html',
        'crawl_frequency': 'daily',
        'trust_level': 'high',
        'region': 'Italy',
    },
    {
        'domain': 'agenziaentrate.gov.it',
        'name': 'Agenzia delle Entrate',
        'source_type': 'website',
        'authority_level': 'tier_1',
        'crawl_method': 'html',
        'crawl_frequency': 'daily',
        'trust_level': 'high',
        'region': 'Italy',
    },
    {
        'domain': 'simest.it',
        'name': 'SIMEST',
        'source_type': 'website',
        'authority_level': 'tier_1',
        'crawl_method': 'html',
        'crawl_frequency': 'daily',
        'trust_level': 'high',
        'region': 'Italy',
    },
    {
        'domain': 'gse.it',
        'name': 'GSE',
        'source_type': 'website',
        'authority_level': 'tier_1',
        'crawl_method': 'html',
        'crawl_frequency': 'daily',
        'trust_level': 'high',
        'region': 'Italy',
    },
    {
        'domain': 'famiglia.gov.it',
        'name': 'Dipartimento per le Politiche della Famiglia',
        'source_type': 'website',
        'authority_level': 'tier_1',
        'crawl_method': 'html',
        'crawl_frequency': 'weekly',
        'trust_level': 'high',
        'region': 'Italy',
    },
]


PROFILE_FACT_SPECS = [
    {
        'key': 'profile_type',
        'label': 'Quale profilo ti descrive meglio?',
        'module': SurveyModule.CORE_ENTITY.value,
        'value_kind': 'select',
        'options': ['persona_fisica', 'freelancer', 'startup', 'sme', 'advisor'],
        'helper_text': 'Serve per capire quali famiglie di misure possono riguardarti davvero.',
        'why_needed': 'Tutte le misure distinguono tra persona fisica, freelance, startup e PMI.',
        'stable': True,
        'sensitive': False,
        'required_in_core': True,
        'depends_on': None,
        'sort_order': 10,
    },
    {
        'key': 'activity_stage',
        'label': "In che stato e la tua attivita?",
        'module': SurveyModule.CORE_ENTITY.value,
        'value_kind': 'select',
        'options': ['not_started', 'partita_iva_only', 'incorporated_business'],
        'helper_text': 'Distingue progetto in avvio, attivita individuale e impresa gia costituita.',
        'why_needed': 'Molte misure cambiano in base al fatto che l’attivita sia solo avviata, professionale o societaria.',
        'stable': True,
        'sensitive': False,
        'required_in_core': True,
        'depends_on': None,
        'sort_order': 20,
    },
    {
        'key': 'legal_form_bucket',
        'label': 'Qual e la tua forma giuridica principale?',
        'module': SurveyModule.CORE_ENTITY.value,
        'value_kind': 'select',
        'options': ['individual_professional', 'sole_proprietorship', 'srl', 'innovative_startup', 'cooperative', 'other', 'not_sure'],
        'helper_text': 'La forma giuridica e spesso un vincolo esplicito del bando o del regime.',
        'why_needed': 'Le regole cambiano per liberi professionisti, ditte individuali e societa.',
        'stable': True,
        'sensitive': False,
        'required_in_core': True,
        'depends_on': None,
        'sort_order': 30,
    },
    {
        'key': 'main_operating_region',
        'label': 'In quale regione operi principalmente?',
        'module': SurveyModule.CORE_ENTITY.value,
        'value_kind': 'select',
        'options': ['Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Emilia-Romagna', 'Friuli-Venezia Giulia', 'Lazio', 'Liguria', 'Lombardia', 'Marche', 'Molise', 'Piemonte', 'Puglia', 'Sardegna', 'Sicilia', 'Toscana', 'Trentino-Alto Adige', 'Umbria', "Valle d'Aosta", 'Veneto'],
        'helper_text': 'Le misure nazionali spesso hanno ramificazioni geografiche e filtri Sud/ZES.',
        'why_needed': 'Serve a distinguere misure nazionali con priorita territoriali.',
        'stable': True,
        'sensitive': False,
        'required_in_core': True,
        'depends_on': None,
        'sort_order': 40,
    },
    {
        'key': 'company_age_or_formation_window',
        'label': 'Da quanto esiste l’attivita o quanto manca alla costituzione?',
        'module': SurveyModule.CORE_ENTITY.value,
        'value_kind': 'select',
        'options': ['idea', '0-12m', '1-3y', '3-5y', '5y+', 'not_sure'],
        'helper_text': 'Fondamentale per nuove imprese, startup e misure di autoimpiego.',
        'why_needed': 'Molte famiglie di misure hanno soglie di anzianita o si rivolgono solo a nuove iniziative.',
        'stable': True,
        'sensitive': False,
        'required_in_core': True,
        'depends_on': None,
        'sort_order': 50,
    },
    {
        'key': 'size_band',
        'label': 'Quanto e grande oggi la struttura?',
        'module': SurveyModule.CORE_ENTITY.value,
        'value_kind': 'select',
        'options': ['solo', 'micro', 'small', 'medium', 'not_sure'],
        'helper_text': 'Usato per distinguere microimprese, PMI e attivita individuali.',
        'why_needed': 'Le misure nazionali hanno quasi sempre una dimensione target.',
        'stable': True,
        'sensitive': False,
        'required_in_core': True,
        'depends_on': None,
        'sort_order': 60,
    },
    {
        'key': 'sector_macro_category',
        'label': 'Qual e il settore principale?',
        'module': SurveyModule.CORE_ENTITY.value,
        'value_kind': 'select',
        'options': ['digitale', 'manifattura', 'servizi', 'turismo', 'retail', 'energia', 'agritech', 'creative', 'other'],
        'helper_text': 'Aiuta a far emergere misure verticali o esclusioni settoriali.',
        'why_needed': 'Molti incentivi sono verticali o escludono alcuni codici/cluster di settore.',
        'stable': True,
        'sensitive': False,
        'required_in_core': True,
        'depends_on': None,
        'sort_order': 70,
    },
    {
        'key': 'innovation_regime_status',
        'label': 'Hai gia lo status di startup innovativa o PMI innovativa?',
        'module': SurveyModule.CORE_ENTITY.value,
        'value_kind': 'select',
        'options': ['none', 'startup_innovativa', 'pmi_innovativa', 'not_sure'],
        'helper_text': 'Questo status apre o chiude intere famiglie di misure.',
        'why_needed': 'E un discriminante forte per diversi incentivi nazionali e regimi dedicati.',
        'stable': True,
        'sensitive': False,
        'required_in_core': True,
        'depends_on': None,
        'sort_order': 80,
    },
    {
        'key': 'employment_type',
        'label': "Qual è la tua situazione lavorativa principale?",
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['dipendente', 'autonomo', 'disoccupato', 'pensionato'],
        'helper_text': 'Determina quali famiglie di misure INPS e fiscali si applicano a te.',
        'why_needed': 'NASpI, ANF e regime forfettario dipendono direttamente dal tipo di rapporto lavorativo.',
        'stable': True,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'profile_type': ['persona_fisica']},
        'sort_order': 85,
    },
    {
        'key': 'isee_bracket',
        'label': "In quale fascia ISEE rientra il tuo nucleo familiare?",
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['under_15k', '15_25k', '25_40k', 'over_40k', 'non_determinato'],
        'helper_text': 'Fascia fondamentale per Assegno Unico, bonus nido e altri benefici reddituali.',
        'why_needed': "Molte misure INPS e fiscali hanno soglie ISEE esplicite che cambiano l'importo o l'accesso.",
        'stable': True,
        'sensitive': True,
        'required_in_core': False,
        'depends_on': {'profile_type': ['persona_fisica']},
        'sort_order': 88,
    },
    {
        'key': 'family_composition',
        'label': "Com'è composto il tuo nucleo familiare?",
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['single', 'coppia_senza_figli', 'coppia_con_figli', 'genitore_solo_con_figli'],
        'helper_text': 'Determina accesso a Assegno Unico, ANF, detrazioni per figli e bonus nido.',
        'why_needed': 'I benefici familiari dipendono dalla composizione del nucleo, non solo dal reddito.',
        'stable': True,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'profile_type': ['persona_fisica']},
        'sort_order': 90,
    },
    {
        'key': 'figli_a_carico_count',
        'label': 'Quanti figli hai a carico?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['0', '1', '2', '3_plus'],
        'helper_text': "Il numero di figli cambia l'importo di Assegno Unico, detrazioni e bonus nido.",
        'why_needed': 'Quasi tutte le misure familiari scalano per numero di figli.',
        'stable': True,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'profile_type': ['persona_fisica']},
        'sort_order': 92,
    },
    {
        'key': 'persona_fisica_age_band',
        'label': "In quale fascia d'età rientri?",
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['under_35', '35_55', 'over_55'],
        'helper_text': "Alcune misure come il bonus prima casa under 36 e le agevolazioni forfettarie dipendono dall'età.",
        'why_needed': "Molti benefici fiscali e contributivi hanno soglie anagrafiche esplicite.",
        'stable': True,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'profile_type': ['persona_fisica']},
        'sort_order': 94,
    },
    {
        'key': 'hiring_interest',
        'label': 'Stai pianificando assunzioni nei prossimi 12 mesi?',
        'module': SurveyModule.STRATEGIC_INTENT.value,
        'value_kind': 'boolean',
        'options': ['true', 'false'],
        'helper_text': 'Attiva il modulo dedicato agli incentivi per l’occupazione.',
        'why_needed': 'Serve a non chiedere dettagli sui lavoratori target se non stai assumendo.',
        'stable': False,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': None,
        'sort_order': 110,
    },
    {
        'key': 'export_investment_intent',
        'label': 'Hai un progetto concreto di export o internazionalizzazione?',
        'module': SurveyModule.STRATEGIC_INTENT.value,
        'value_kind': 'boolean',
        'options': ['true', 'false'],
        'helper_text': 'Usato per sbloccare le famiglie SIMEST e i relativi dettagli.',
        'why_needed': 'Le misure export dipendono molto dal progetto, non solo dal profilo aziendale.',
        'stable': False,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': None,
        'sort_order': 120,
    },
    {
        'key': 'digital_transition_project',
        'label': 'Hai un progetto concreto di digitalizzazione o trasformazione tecnologica?',
        'module': SurveyModule.STRATEGIC_INTENT.value,
        'value_kind': 'boolean',
        'options': ['true', 'false'],
        'helper_text': 'Serve a distinguere interesse generico da investimento progettuale reale.',
        'why_needed': 'Crediti e voucher digitali richiedono spesso un investimento o progetto definito.',
        'stable': False,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': None,
        'sort_order': 130,
    },
    {
        'key': 'energy_transition_project',
        'label': 'Hai un progetto concreto su energia, efficienza o transizione green?',
        'module': SurveyModule.STRATEGIC_INTENT.value,
        'value_kind': 'boolean',
        'options': ['true', 'false'],
        'helper_text': 'Attiva le domande specifiche su efficienza energetica e Transizione 5.0.',
        'why_needed': 'Le misure green e 5.0 dipendono da investimenti e obiettivi di risparmio energetico.',
        'stable': False,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': None,
        'sort_order': 140,
    },
    {
        'key': 'patent_ip_intent',
        'label': 'Hai o stai pianificando brevetti, tutela IP o valorizzazione tecnologica?',
        'module': SurveyModule.STRATEGIC_INTENT.value,
        'value_kind': 'boolean',
        'options': ['true', 'false'],
        'helper_text': 'Usato per misure legate a brevetti, voucher 3I e R&D.',
        'why_needed': 'Serve a individuare misure orientate a proprieta intellettuale e innovazione protetta.',
        'stable': False,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': None,
        'sort_order': 150,
    },
    {
        'key': 'women_led_majority',
        'label': 'La maggioranza del controllo o della leadership e femminile?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'boolean',
        'options': ['true', 'false'],
        'helper_text': 'Richiesto solo da famiglie di misure dove questo criterio cambia l’eleggibilita.',
        'why_needed': 'Alcune misure dedicano canali o priorita a imprenditoria femminile.',
        'stable': True,
        'sensitive': True,
        'required_in_core': False,
        'depends_on': None,
        'sort_order': 210,
    },
    {
        'key': 'founder_age_band',
        'label': 'In quale fascia di eta ricadi tu o il promotore principale?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['under_35', '35_55', '55_plus'],
        'helper_text': 'Mostrata solo quando misure di autoimpiego o assunzione dipendono dall’eta.',
        'why_needed': 'Alcuni incentivi nazionali hanno soglie anagrafiche esplicite.',
        'stable': True,
        'sensitive': True,
        'required_in_core': False,
        'depends_on': None,
        'sort_order': 220,
    },
    {
        'key': 'unemployment_status_at_start',
        'label': 'Alla partenza del progetto eri disoccupato o fuori dal mercato del lavoro?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['yes', 'no', 'not_applicable', 'not_sure'],
        'helper_text': 'Usato solo su misure di autoimpiego e inclusione lavorativa.',
        'why_needed': 'Alcuni incentivi richiedono una condizione lavorativa specifica al momento di avvio.',
        'stable': True,
        'sensitive': True,
        'required_in_core': False,
        'depends_on': {'activity_stage': ['not_started', 'partita_iva_only', 'incorporated_business']},
        'sort_order': 230,
    },
    {
        'key': 'no_prior_permanent_employment',
        'label': 'Il soggetto rilevante non ha avuto rapporti a tempo indeterminato recenti?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['yes', 'no', 'not_sure'],
        'helper_text': 'Serve a perfezionare alcuni incentivi di inserimento e autoimpiego.',
        'why_needed': 'Alcune misure definiscono beneficiari e lavoratori target con vincoli occupazionali pregressi.',
        'stable': False,
        'sensitive': True,
        'required_in_core': False,
        'depends_on': None,
        'sort_order': 240,
    },
    {
        'key': 'target_hire_age_band',
        'label': 'Se assumi, il profilo target rientra in una fascia di eta agevolata?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['under_35', '35_plus', 'mixed', 'not_sure'],
        'helper_text': 'Appare solo se stai cercando incentivi all’assunzione.',
        'why_needed': 'Bonus giovani e altre misure dipendono dalle caratteristiche del lavoratore assunto, non dell’azienda.',
        'stable': False,
        'sensitive': True,
        'required_in_core': False,
        'depends_on': {'hiring_interest': ['true']},
        'sort_order': 250,
    },
    {
        'key': 'target_hire_gender_priority',
        'label': 'Il profilo di assunzione target rientra in un canale donna o categoria equiparata?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['female_target', 'mixed', 'none', 'not_sure'],
        'helper_text': 'Usato solo per misure occupazionali dedicate.',
        'why_needed': 'Bonus donne e misure affini dipendono dal profilo del lavoratore target.',
        'stable': False,
        'sensitive': True,
        'required_in_core': False,
        'depends_on': {'hiring_interest': ['true']},
        'sort_order': 260,
    },
    {
        'key': 'target_hire_disadvantaged_status',
        'label': 'Il profilo target rientra in una categoria lavorativa svantaggiata o prioritaria?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['yes', 'no', 'not_sure'],
        'helper_text': 'Attivato solo per valutare incentivi all’occupazione mirati.',
        'why_needed': 'Alcuni incentivi occupazionali dipendono dallo status del lavoratore da assumere.',
        'stable': False,
        'sensitive': True,
        'required_in_core': False,
        'depends_on': {'hiring_interest': ['true']},
        'sort_order': 270,
    },
    {
        'key': 'target_market_scope',
        'label': 'Il progetto export riguarda UE, extra-UE o entrambi?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['eu', 'extra_eu', 'both', 'not_sure'],
        'helper_text': 'Mostrata solo quando emerge un progetto di internazionalizzazione.',
        'why_needed': 'Alcune misure export richiedono maggiore dettaglio sul mercato target.',
        'stable': False,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'export_investment_intent': ['true']},
        'sort_order': 280,
    },
    {
        'key': 'energy_reduction_goal',
        'label': 'Il progetto energetico mira a un miglioramento misurabile dei consumi?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['yes', 'no', 'not_sure'],
        'helper_text': 'Richiesto solo su crediti e misure con vincolo di performance energetica.',
        'why_needed': 'Transizione 5.0 e misure simili dipendono da obiettivi energetici verificabili.',
        'stable': False,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'energy_transition_project': ['true']},
        'sort_order': 290,
    },
    {
        'key': 'filed_balance_sheets_count',
        'label': 'Quanti bilanci completi risultano gia depositati?',
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['0', '1', '2_plus', 'not_applicable', 'not_sure'],
        'helper_text': 'Attivato solo per distinguere alcuni regimi e linee destinate a societa gia mature.',
        'why_needed': 'Alcuni regimi o misure operative richiedono anzianita societaria documentata.',
        'stable': False,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'activity_stage': ['incorporated_business']},
        'sort_order': 300,
    },
    {
        'key': 'home_ownership_status',
        'label': "Qual è il tuo rapporto con l'abitazione principale?",
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['proprietario', 'inquilino_contratto_registrato', 'comodato_uso', 'altro'],
        'helper_text': "Serve per ristrutturazione 50%, Ecobonus, detrazione mutuo e detrazione affitto.",
        'why_needed': "Molte detrazioni fiscali legate alla casa distinguono proprietari, inquilini e comodatari.",
        'stable': True,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'profile_type': ['persona_fisica']},
        'sort_order': 95,
    },
    {
        'key': 'youngest_child_age_band',
        'label': "Qual è l'età del figlio più piccolo?",
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['under_3', 'da_3_a_21', 'over_21'],
        'helper_text': "Il Bonus Nido INPS richiede un figlio under 3 anni.",
        'why_needed': "Il Contributo Asilo Nido INPS è limitato ai bambini sotto i 3 anni.",
        'stable': True,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'figli_a_carico_count': ['1', '2', '3_plus']},
        'sort_order': 96,
    },
    {
        'key': 'disability_status',
        'label': "Hai o hai in famiglia una persona con disabilità certificata?",
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['nessuna', 'legge_104_in_famiglia', 'invalidita_civile', 'indennita_accompagnamento'],
        'helper_text': "Necessario per Legge 104, permessi retribuiti, detrazioni auto H e assegni INPS.",
        'why_needed': "Le agevolazioni per disabilità dipendono dal tipo di riconoscimento INPS/ASL.",
        'stable': True,
        'sensitive': True,
        'required_in_core': False,
        'depends_on': {'profile_type': ['persona_fisica']},
        'sort_order': 97,
    },
    {
        'key': 'tax_regime_freelancer',
        'label': "Qual è il tuo regime fiscale attuale?",
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['forfettario', 'regime_ordinario', 'non_ancora_aperto'],
        'helper_text': "Il regime forfettario cambia contributi, IVA e accesso a misure INPS specifiche.",
        'why_needed': "L'esonero contributivo under 35 e altri incentivi dipendono dal regime fiscale.",
        'stable': False,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'employment_type': ['autonomo']},
        'sort_order': 86,
    },
    {
        'key': 'has_mortgage',
        'label': "Hai un mutuo attivo sulla prima casa?",
        'module': SurveyModule.CONDITIONAL_ACCURACY.value,
        'value_kind': 'select',
        'options': ['si', 'no'],
        'helper_text': "Necessario per la detrazione degli interessi passivi del mutuo.",
        'why_needed': "La detrazione IRPEF sugli interessi del mutuo prima casa richiede un mutuo attivo.",
        'stable': True,
        'sensitive': False,
        'required_in_core': False,
        'depends_on': {'home_ownership_status': ['proprietario']},
        'sort_order': 98,
    },
]


MEASURE_FAMILY_SPECS = [
    {
        'slug': 'startup_innovativa_status',
        'title': 'Startup innovativa',
        'operator_name': 'MIMIT',
        'source_domain': 'mimit.gov.it',
        'is_regime_only': True,
        'is_actionable': False,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'eligibility_regime',
        'benefit_magnitude_model': 'regime_status',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup'],
        'size_constraints': ['micro', 'small'],
        'sector_constraints': ['digitale', 'energia', 'agritech', 'manifattura', 'servizi'],
        'legal_form_constraints': ['srl', 'innovative_startup'],
        'regime_status_constraints': ['startup_innovativa'],
        'age_or_time_constraints': ['0-12m', '1-3y', '3-5y'],
        'person_specific_constraints': None,
        'project_specific_constraints': ['innovazione_tecnologica'],
        'application_mechanics': {'channel': 'registro_imprese', 'portal': 'startup.registroimprese.it'},
        'required_documents': ['Atto costitutivo', 'Autocertificazione requisiti innovazione'],
        'entrypoint_urls': ['https://www.mimit.gov.it/it/startup-innovative'],
        'allowed_path_keywords': ['startup', 'innovative', 'registro', 'faq'],
        'evidence_snippets': [{'field': 'status', 'quote': 'Regime speciale per societa innovative con requisiti normativi dedicati.'}],
        'documents': [
            doc('https://www.mimit.gov.it/it/startup-innovative', 'MIMIT - Startup innovative', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Pagina istituzionale con requisiti, vantaggi e accesso al regime startup innovativa.'),
            doc('https://www.normattiva.it/uri-res/N2Ls?urn%3Anir%3Astato%3Adecreto.legge%3A2012-10-18%3B179~art25%21vig=', 'Normattiva - D.L. 179/2012 art. 25', DocumentRole.LEGAL_BASIS.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_legal_basis', 'Testo normativo consolidato del regime startup innovativa.'),
            doc('https://www.gazzettaufficiale.it/eli/id/2012/12/18/12G0213/sg', 'Gazzetta Ufficiale - D.L. 179/2012', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Pubblicazione iniziale del decreto che introduce il quadro startup innovativa.'),
            doc('https://startup.registroimprese.it/isin/static/startup/index.html', 'Registro Imprese - Sezione speciale startup innovative', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'application_channel', 'Portale operativo per iscrizione e gestione della sezione speciale.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['startup']),
            req('activity_stage', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['incorporated_business']),
            req('legal_form_bucket', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['srl', 'innovative_startup']),
            req('company_age_or_formation_window', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['0-12m', '1-3y', '3-5y']),
            req('innovation_regime_status', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['startup_innovativa', 'not_sure']),
            req('digital_transition_project', RequirementMode.RANKING_OR_BOOSTER.value, ['true']),
            req('patent_ip_intent', RequirementMode.RANKING_OR_BOOSTER.value, ['true']),
        ],
    },
    {
        'slug': 'pmi_innovativa_status',
        'title': 'PMI innovativa',
        'operator_name': 'MIMIT',
        'source_domain': 'mimit.gov.it',
        'is_regime_only': True,
        'is_actionable': False,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'eligibility_regime',
        'benefit_magnitude_model': 'regime_status',
        'geography': 'Italy',
        'beneficiary_entity_types': ['sme', 'startup'],
        'size_constraints': ['micro', 'small', 'medium'],
        'sector_constraints': None,
        'legal_form_constraints': ['srl', 'other'],
        'regime_status_constraints': ['pmi_innovativa'],
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': ['innovazione_tecnologica'],
        'application_mechanics': {'channel': 'registro_imprese', 'portal': 'startup.registroimprese.it'},
        'required_documents': ['Autodichiarazione requisiti PMI innovativa'],
        'entrypoint_urls': ['https://www.mimit.gov.it/it/startup-innovative'],
        'allowed_path_keywords': ['pmi', 'innovative', 'registro', 'faq'],
        'evidence_snippets': [{'field': 'status', 'quote': 'Regime per PMI con requisiti di innovazione non limitato alla fase seed.'}],
        'documents': [
            doc('https://www.mimit.gov.it/it/startup-innovative', 'MIMIT - Startup innovative e PMI innovative', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Sezione istituzionale dedicata ai regimi innovativi con riferimenti a startup e PMI innovative.'),
            doc('https://www.normattiva.it/uri-res/N2Ls?urn%3Anir%3Astato%3Adecreto.legge%3A2015-01-24%3B3', 'Normattiva - D.L. 3/2015', DocumentRole.LEGAL_BASIS.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_legal_basis', 'Norma di riferimento per l’estensione del regime alle PMI innovative.'),
            doc('https://www.gazzettaufficiale.it/eli/id/2015/03/24/15G00039/sg', 'Gazzetta Ufficiale - D.L. 3/2015', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Pubblicazione del decreto di base sulle PMI innovative.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['sme', 'startup']),
            req('activity_stage', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['incorporated_business']),
            req('size_band', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['micro', 'small', 'medium']),
            req('innovation_regime_status', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['pmi_innovativa', 'not_sure']),
            req('filed_balance_sheets_count', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['1', '2_plus', 'not_sure']),
        ],
    },
    {
        'slug': 'smart_start_italia',
        'title': 'Smart&Start Italia',
        'operator_name': 'Invitalia',
        'source_domain': 'invitalia.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'finanziamento_agevolato',
        'benefit_magnitude_model': 'loan_plus_support',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup'],
        'size_constraints': ['micro', 'small'],
        'sector_constraints': ['digitale', 'energia', 'agritech', 'manifattura', 'servizi'],
        'legal_form_constraints': ['innovative_startup', 'srl'],
        'regime_status_constraints': ['startup_innovativa', 'not_sure'],
        'age_or_time_constraints': ['idea', '0-12m', '1-3y'],
        'person_specific_constraints': None,
        'project_specific_constraints': ['innovazione_tecnologica', 'business_plan'],
        'application_mechanics': {'channel': 'invitalia_portal', 'timing': 'sportello'},
        'required_documents': ['Business plan', 'Pitch deck', 'Dati societari'],
        'entrypoint_urls': ['https://www.invitalia.it/incentivi-e-strumenti/smartstart-italia'],
        'allowed_path_keywords': ['smart', 'start', 'faq', 'guide', 'modulistica'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Misura nazionale per startup innovative con piano di investimento e crescita.'}],
        'documents': [
            doc('https://www.invitalia.it/incentivi-e-strumenti/smartstart-italia', 'Invitalia - Smart&Start Italia', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Scheda operativa del finanziamento Smart&Start Italia.'),
            doc('https://www.invitalia.it/incentivi-e-strumenti/smartstart-italia/faq', 'Invitalia - FAQ Smart&Start Italia', DocumentRole.FAQ_OR_OPERATIONAL_GUIDE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'supporting_document', 'Domande frequenti operative e interpretative sulla misura.'),
            doc('https://www.mimit.gov.it/it/startup-innovative', 'MIMIT - Startup innovative', DocumentRole.IMPLEMENTING_DECREE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'supporting_eligibility_regime', 'Riferimento istituzionale sul regime di startup innovativa richiesto dalla misura.'),
            doc('https://www.normattiva.it/uri-res/N2Ls?urn%3Anir%3Astato%3Adecreto.legge%3A2012-10-18%3B179~art25%21vig=', 'Normattiva - Base regime startup innovativa', DocumentRole.LEGAL_BASIS.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_legal_basis', 'Base normativa utilizzata per il perimetro delle startup innovative.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['startup']),
            req('activity_stage', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['not_started', 'incorporated_business']),
            req('size_band', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['micro', 'small']),
            req('innovation_regime_status', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['startup_innovativa', 'not_sure']),
            req('digital_transition_project', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('patent_ip_intent', RequirementMode.RANKING_OR_BOOSTER.value, ['true']),
        ],
    },
    {
        'slug': 'on_oltre_nuove_imprese_a_tasso_zero',
        'title': 'ON - Oltre Nuove imprese a tasso zero',
        'operator_name': 'Invitalia',
        'source_domain': 'invitalia.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'mutuo_agevolato',
        'benefit_magnitude_model': 'loan_plus_grant',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme'],
        'size_constraints': ['micro', 'small'],
        'sector_constraints': ['servizi', 'turismo', 'manifattura', 'retail'],
        'legal_form_constraints': ['srl', 'sole_proprietorship', 'cooperative'],
        'regime_status_constraints': None,
        'age_or_time_constraints': ['idea', '0-12m'],
        'person_specific_constraints': ['giovani_o_donne'],
        'project_specific_constraints': ['business_plan'],
        'application_mechanics': {'channel': 'invitalia_portal', 'timing': 'sportello'},
        'required_documents': ['Business plan', 'Documento identita', 'Preventivi spesa'],
        'entrypoint_urls': ['https://www.invitalia.it/incentivi-e-strumenti/nuove-imprese-a-tasso-zero'],
        'allowed_path_keywords': ['nuove-imprese', 'tasso-zero', 'faq', 'modulistica'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Sostegno per nuove iniziative imprenditoriali con mix di finanziamento e contributo.'}],
        'documents': [
            doc('https://www.invitalia.it/incentivi-e-strumenti/nuove-imprese-a-tasso-zero', 'Invitalia - ON Oltre Nuove imprese a tasso zero', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Scheda misura per nuove imprese con finanziamento agevolato.'),
            doc('https://www.invitalia.it/incentivi-e-strumenti/nuove-imprese-a-tasso-zero/faq', 'Invitalia - FAQ ON', DocumentRole.FAQ_OR_OPERATIONAL_GUIDE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'supporting_document', 'FAQ operative sui requisiti della misura.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - pubblicazione misura ON', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Traccia di pubblicazione e aggiornamenti regolatori della misura.'),
            doc('https://www.invitalia.it/', 'Invitalia - Portale domanda ON', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'application_channel', 'Portale di accesso alla domanda telematica.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['startup', 'sme']),
            req('activity_stage', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['not_started', 'incorporated_business']),
            req('company_age_or_formation_window', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['idea', '0-12m']),
            req('legal_form_bucket', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['sole_proprietorship', 'srl', 'cooperative', 'other']),
            req('founder_age_band', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['under_35'], 'Può essere rilevante per il canale giovani.'),
            req('women_led_majority', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['true'], 'Può essere rilevante per il canale imprenditoria femminile.'),
        ],
    },
    {
        'slug': 'resto_al_sud_2_0',
        'title': 'Resto al Sud 2.0',
        'operator_name': 'Invitalia',
        'source_domain': 'invitalia.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.SCHEDULED.value,
        'benefit_kind': 'self_employment_support',
        'benefit_magnitude_model': 'grant_plus_services',
        'geography': 'Italy',
        'beneficiary_entity_types': ['freelancer', 'startup'],
        'size_constraints': ['solo', 'micro'],
        'sector_constraints': ['servizi', 'turismo', 'retail', 'digitale'],
        'legal_form_constraints': ['individual_professional', 'sole_proprietorship', 'srl'],
        'regime_status_constraints': None,
        'age_or_time_constraints': ['idea', '0-12m'],
        'person_specific_constraints': ['under_35', 'disoccupazione'],
        'project_specific_constraints': ['self_employment'],
        'application_mechanics': {'channel': 'invitalia_portal', 'timing': 'band_window'},
        'required_documents': ['Documento identita', 'Descrizione progetto', 'Residenza/operativita aree ammissibili'],
        'entrypoint_urls': ['https://www.invitalia.it/'],
        'allowed_path_keywords': ['resto', 'sud', 'autoimpiego', 'faq'],
        'evidence_snippets': [{'field': 'geography', 'quote': 'Misura orientata a nuova imprenditorialita e autoimpiego nelle aree target del Mezzogiorno.'}],
        'documents': [
            doc('https://www.invitalia.it/', 'Invitalia - Area incentivi autoimpiego Sud', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.SCHEDULED.value, 'primary_operational', 'Area Invitalia per misure di autoimpiego e imprenditorialita nel Sud.'),
            doc('https://www.normattiva.it/eli/id/2024/05/07/24G00077/ORIGINAL', 'Normattiva - D.L. 60/2024', DocumentRole.LEGAL_BASIS.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_legal_basis', 'Decreto Coesione che introduce nuove linee di autoimpiego e sostegno.'),
            doc('https://www.gazzettaufficiale.it/eli/id/2024/05/07/24G00077/sg', 'Gazzetta Ufficiale - D.L. 60/2024', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Pubblicazione iniziale del Decreto Coesione.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['freelancer', 'startup']),
            req('main_operating_region', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Molise', 'Puglia', 'Sardegna', 'Sicilia']),
            req('activity_stage', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['not_started', 'partita_iva_only']),
            req('founder_age_band', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['under_35']),
            req('unemployment_status_at_start', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['yes', 'not_sure']),
        ],
    },
    {
        'slug': 'autoimpiego_centro_nord',
        'title': 'Autoimpiego Centro-Nord',
        'operator_name': 'Invitalia',
        'source_domain': 'invitalia.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.SCHEDULED.value,
        'benefit_kind': 'self_employment_support',
        'benefit_magnitude_model': 'grant_plus_services',
        'geography': 'Italy',
        'beneficiary_entity_types': ['freelancer', 'startup'],
        'size_constraints': ['solo', 'micro'],
        'sector_constraints': ['servizi', 'digitale', 'retail', 'creative'],
        'legal_form_constraints': ['individual_professional', 'sole_proprietorship', 'srl'],
        'regime_status_constraints': None,
        'age_or_time_constraints': ['idea', '0-12m'],
        'person_specific_constraints': ['under_35', 'disoccupazione'],
        'project_specific_constraints': ['self_employment'],
        'application_mechanics': {'channel': 'invitalia_portal', 'timing': 'band_window'},
        'required_documents': ['Documento identita', 'Descrizione progetto'],
        'entrypoint_urls': ['https://www.invitalia.it/'],
        'allowed_path_keywords': ['autoimpiego', 'centro', 'nord', 'giovani'],
        'evidence_snippets': [{'field': 'geography', 'quote': 'Linea di autoimpiego orientata a nuove iniziative in Centro-Nord.'}],
        'documents': [
            doc('https://www.invitalia.it/', 'Invitalia - Area autoimpiego Centro-Nord', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.SCHEDULED.value, 'primary_operational', 'Area operativa per le nuove linee di autoimpiego fuori dal Mezzogiorno.'),
            doc('https://www.normattiva.it/eli/id/2024/05/07/24G00077/ORIGINAL', 'Normattiva - D.L. 60/2024', DocumentRole.LEGAL_BASIS.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_legal_basis', 'Decreto di base per le linee di autoimpiego giovani.'),
            doc('https://www.inps.it/it/it/inps-comunica/notizie/dettaglio-news-page.news.2026.01.bonus-500-euro-anche-per-i-liberi-professionisti-under-35.html', 'INPS - Bonus per liberi professionisti under 35', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'supporting_document', 'Aggiornamento operativo INPS collegato al perimetro giovani/liberi professionisti.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['freelancer', 'startup']),
            req('main_operating_region', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['Lazio', 'Lombardia', 'Veneto', 'Piemonte', 'Toscana', 'Emilia-Romagna', 'Liguria', 'Marche', 'Umbria', 'Abruzzo', 'Friuli-Venezia Giulia', 'Trentino-Alto Adige', "Valle d'Aosta"]),
            req('activity_stage', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['not_started', 'partita_iva_only']),
            req('founder_age_band', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['under_35']),
            req('unemployment_status_at_start', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['yes', 'not_sure']),
        ],
    },
    {
        'slug': 'bonus_liberi_professionisti_under35',
        'title': 'Bonus liberi professionisti under 35',
        'operator_name': 'INPS',
        'source_domain': 'inps.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'direct_bonus',
        'benefit_magnitude_model': 'fixed_amount',
        'geography': 'Italy',
        'beneficiary_entity_types': ['freelancer'],
        'size_constraints': ['solo'],
        'sector_constraints': ['servizi', 'digitale', 'creative', 'other'],
        'legal_form_constraints': ['individual_professional'],
        'regime_status_constraints': None,
        'age_or_time_constraints': ['idea', '0-12m', '1-3y'],
        'person_specific_constraints': ['under_35'],
        'project_specific_constraints': ['self_employment'],
        'application_mechanics': {'channel': 'inps_portal', 'timing': 'window'},
        'required_documents': ['SPID/CIE', 'Partita IVA', 'Dichiarazione requisiti'],
        'entrypoint_urls': ['https://www.inps.it/it/it/inps-comunica/notizie/dettaglio-news-page.news.2026.01.bonus-500-euro-anche-per-i-liberi-professionisti-under-35.html'],
        'allowed_path_keywords': ['professionisti', 'under-35', 'bonus'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Bonus operativo dedicato anche ai liberi professionisti under 35.'}],
        'documents': [
            doc('https://www.inps.it/it/it/inps-comunica/notizie/dettaglio-news-page.news.2026.01.bonus-500-euro-anche-per-i-liberi-professionisti-under-35.html', 'INPS - Bonus 500 euro anche per i liberi professionisti under 35', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Pagina INPS con istruzioni operative sulla misura.'),
            doc('https://www.normattiva.it/eli/id/2024/05/07/24G00077/ORIGINAL', 'Normattiva - D.L. 60/2024', DocumentRole.LEGAL_BASIS.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_legal_basis', 'Base normativa di sostegno alle misure di autoimpiego giovani.'),
            doc('https://www.inps.it/', 'INPS - Portale domanda bonus professionisti', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'application_channel', 'Accesso al portale INPS per istanza e gestione domanda.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['freelancer']),
            req('legal_form_bucket', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['individual_professional']),
            req('founder_age_band', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['under_35']),
            req('activity_stage', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['partita_iva_only']),
        ],
    },
    {
        'slug': 'bonus_giovani_under35',
        'title': 'Bonus giovani under 35',
        'operator_name': 'INPS',
        'source_domain': 'inps.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'hiring_incentive',
        'benefit_magnitude_model': 'contribution_relief',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme', 'freelancer'],
        'size_constraints': ['solo', 'micro', 'small', 'medium'],
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': ['target_hire_under_35'],
        'project_specific_constraints': ['hiring'],
        'application_mechanics': {'channel': 'inps_portal', 'timing': 'operational_window'},
        'required_documents': ['Dati lavoratore', 'Comunicazioni assunzione'],
        'entrypoint_urls': ['https://www.inps.it/it/it/inps-comunica/notizie/dettaglio-news-page.news.2025.05.bonus-giovani-under-35-e-bonus-donne-requisiti-e-modalita-operative.html'],
        'allowed_path_keywords': ['bonus', 'giovani', 'under-35', 'assunzioni'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Esonero contributivo per assunzioni di giovani under 35 con istruzioni operative INPS.'}],
        'documents': [
            doc('https://www.inps.it/it/it/inps-comunica/notizie/dettaglio-news-page.news.2025.05.bonus-giovani-under-35-e-bonus-donne-requisiti-e-modalita-operative.html', 'INPS - Bonus giovani under 35', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Pagina operativa INPS su bonus giovani under 35.'),
            doc('https://www.inps.it/', 'INPS - Portale incentivi assunzione', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'application_channel', 'Portale per gestione bonus occupazionali.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - riferimenti bonus giovani', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Traccia di pubblicazione dei riferimenti normativi.'),
        ],
        'requirements': [
            req('hiring_interest', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('target_hire_age_band', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['under_35', 'mixed', 'not_sure']),
            req('target_hire_disadvantaged_status', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['yes', 'not_sure']),
        ],
    },
    {
        'slug': 'bonus_donne',
        'title': 'Bonus donne',
        'operator_name': 'INPS',
        'source_domain': 'inps.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'hiring_incentive',
        'benefit_magnitude_model': 'contribution_relief',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme', 'freelancer'],
        'size_constraints': ['solo', 'micro', 'small', 'medium'],
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': ['target_hire_female', 'target_hire_disadvantaged'],
        'project_specific_constraints': ['hiring'],
        'application_mechanics': {'channel': 'inps_portal', 'timing': 'operational_window'},
        'required_documents': ['Dati lavoratrice target', 'Comunicazioni assunzione'],
        'entrypoint_urls': ['https://www.inps.it/it/it/inps-comunica/notizie/dettaglio-news-page.news.2025.05.bonus-giovani-under-35-e-bonus-donne-requisiti-e-modalita-operative.html'],
        'allowed_path_keywords': ['bonus', 'donne', 'assunzioni'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Incentivo occupazionale dedicato a specifiche assunzioni femminili.'}],
        'documents': [
            doc('https://www.inps.it/it/it/inps-comunica/notizie/dettaglio-news-page.news.2025.05.bonus-giovani-under-35-e-bonus-donne-requisiti-e-modalita-operative.html', 'INPS - Bonus donne', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Pagina operativa INPS sui requisiti e modalita del bonus donne.'),
            doc('https://www.inps.it/', 'INPS - Portale incentivi assunzione', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'application_channel', 'Portale per istanze bonus donne.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - riferimenti bonus donne', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Traccia regolatoria della misura bonus donne.'),
        ],
        'requirements': [
            req('hiring_interest', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('target_hire_gender_priority', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['female_target', 'mixed', 'not_sure']),
            req('target_hire_disadvantaged_status', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['yes', 'not_sure']),
        ],
    },
    {
        'slug': 'bonus_zes_unica_assunzioni',
        'title': 'Bonus ZES unica assunzioni',
        'operator_name': 'INPS',
        'source_domain': 'inps.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'hiring_incentive',
        'benefit_magnitude_model': 'contribution_relief',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme'],
        'size_constraints': ['micro', 'small', 'medium'],
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': ['target_hire_disadvantaged'],
        'project_specific_constraints': ['hiring_in_zes'],
        'application_mechanics': {'channel': 'inps_portal', 'timing': 'operational_window'},
        'required_documents': ['Dati lavoratore', 'Unita produttiva in area ZES'],
        'entrypoint_urls': ['https://www.inps.it/it/it/inps-comunica/notizie/dettaglio-news-page.news.2026.02.bonus-zes-unica-mezzogiorno-le-istruzioni-operative.html'],
        'allowed_path_keywords': ['zes', 'mezzogiorno', 'assunzioni'],
        'evidence_snippets': [{'field': 'geography', 'quote': 'Misura occupazionale legata ad assunzioni in area ZES unica del Mezzogiorno.'}],
        'documents': [
            doc('https://www.inps.it/it/it/inps-comunica/notizie/dettaglio-news-page.news.2026.02.bonus-zes-unica-mezzogiorno-le-istruzioni-operative.html', 'INPS - Bonus ZES unica Mezzogiorno', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Istruzioni operative INPS sul bonus ZES.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - riferimenti bonus ZES unica', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Riferimenti di pubblicazione e base regolatoria.'),
            doc('https://www.inps.it/', 'INPS - Portale gestione bonus ZES', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'application_channel', 'Portale per invio istanze bonus ZES.'),
        ],
        'requirements': [
            req('main_operating_region', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Molise', 'Puglia', 'Sardegna', 'Sicilia']),
            req('hiring_interest', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('target_hire_disadvantaged_status', RequirementMode.PERSON_SPECIFIC_REQUIREMENT.value, ['yes', 'not_sure']),
        ],
    },
    {
        'slug': 'transizione_5_0',
        'title': 'Piano Transizione 5.0',
        'operator_name': 'MIMIT/GSE',
        'source_domain': 'mimit.gov.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'tax_credit',
        'benefit_magnitude_model': 'project_credit',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme'],
        'size_constraints': ['micro', 'small', 'medium'],
        'sector_constraints': ['digitale', 'manifattura', 'servizi', 'energia'],
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': ['digital_transition_project', 'energy_transition_project', 'energy_reduction_goal'],
        'application_mechanics': {'channel': 'gse_portal', 'timing': 'sportello'},
        'required_documents': ['Progetto investimento', 'Simulazione risparmio energetico', 'Documentazione tecnica'],
        'entrypoint_urls': ['https://www.mimit.gov.it/it/incentivi/piano-transizione-5-0', 'https://assistenza.clienti.gse.it/csm?id=kb_article_view&sysparm_article=KB0017109'],
        'allowed_path_keywords': ['transizione-5-0', 'gse', 'faq', 'guida', 'modulistica'],
        'evidence_snippets': [{'field': 'project', 'quote': 'Credito legato a investimenti digitali con obiettivi misurabili di riduzione dei consumi.'}],
        'documents': [
            doc('https://www.mimit.gov.it/it/incentivi/piano-transizione-5-0', 'MIMIT - Piano Transizione 5.0', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Scheda istituzionale del Piano Transizione 5.0.'),
            doc('https://assistenza.clienti.gse.it/csm?id=kb_article_view&sysparm_article=KB0017109', 'GSE - Piano Transizione 5.0', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'application_channel', 'Chiarimenti pubblici GSE sulla prenotazione del credito d’imposta 5.0.'),
            doc('https://www.normattiva.it/uri-res/N2Ls?urn%3Anir%3Astato%3Adecreto.legge%3A2024-03-02%3B19~art38=', 'Normattiva - D.L. 19/2024 art. 38', DocumentRole.LEGAL_BASIS.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_legal_basis', 'Base normativa del credito Transizione 5.0.'),
            doc('https://www.gse.it/', 'GSE - FAQ e guide 5.0', DocumentRole.FAQ_OR_OPERATIONAL_GUIDE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'supporting_document', 'Guide operative e FAQ di attuazione sul 5.0.'),
        ],
        'requirements': [
            req('digital_transition_project', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('energy_transition_project', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('energy_reduction_goal', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['yes', 'not_sure']),
            req('size_band', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['micro', 'small', 'medium']),
        ],
    },
    {
        'slug': 'transizione_4_0_beni_strumentali',
        'title': 'Transizione 4.0 - beni strumentali',
        'operator_name': 'Agenzia delle Entrate / MIMIT',
        'source_domain': 'agenziaentrate.gov.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'tax_credit',
        'benefit_magnitude_model': 'investment_credit',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme'],
        'size_constraints': ['micro', 'small', 'medium'],
        'sector_constraints': ['manifattura', 'digitale', 'servizi'],
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': ['digital_transition_project'],
        'application_mechanics': {'channel': 'fiscal_claim'},
        'required_documents': ['Fatture', 'Perizia o attestazione tecnica', 'Documentazione investimento'],
        'entrypoint_urls': ['https://www.agenziaentrate.gov.it/portale/credito-d-imposta-beni-strumentali'],
        'allowed_path_keywords': ['beni', 'strumentali', '4.0', 'credito'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Credito d’imposta per investimenti in beni strumentali materiali e immateriali 4.0.'}],
        'documents': [
            doc('https://www.agenziaentrate.gov.it/portale/credito-d-imposta-beni-strumentali', 'Agenzia Entrate - Credito beni strumentali', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Scheda fiscale e operativa sul credito beni strumentali.'),
            doc('https://www.mimit.gov.it/it/incentivi/piano-transizione-4-0', 'MIMIT - Piano Transizione 4.0', DocumentRole.MINISTERIAL_CIRCULAR.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'supporting_document', 'Quadro istituzionale del piano 4.0.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - riferimenti Transizione 4.0', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Riferimenti pubblici agli aggiornamenti normativi del 4.0.'),
        ],
        'requirements': [
            req('digital_transition_project', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('size_band', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['micro', 'small', 'medium']),
            req('sector_macro_category', RequirementMode.RANKING_OR_BOOSTER.value, ['digitale', 'manifattura', 'servizi']),
        ],
    },
    {
        'slug': 'credito_rs_innovazione_design',
        'title': 'Credito ricerca, sviluppo, innovazione e design',
        'operator_name': 'Agenzia delle Entrate / MIMIT',
        'source_domain': 'agenziaentrate.gov.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'tax_credit',
        'benefit_magnitude_model': 'project_credit',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme'],
        'size_constraints': ['micro', 'small', 'medium'],
        'sector_constraints': ['digitale', 'agritech', 'energia', 'manifattura', 'creative'],
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': ['digital_transition_project', 'patent_ip_intent'],
        'application_mechanics': {'channel': 'fiscal_claim'},
        'required_documents': ['Documentazione costi R&D', 'Relazione tecnica progetto'],
        'entrypoint_urls': ['https://www.mimit.gov.it/it/incentivi/credito-d-imposta-r-s'],
        'allowed_path_keywords': ['ricerca', 'sviluppo', 'innovazione', 'design'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Credito fiscale per ricerca, sviluppo, innovazione e design con perimetro tecnico preciso.'}],
        'documents': [
            doc('https://www.mimit.gov.it/it/incentivi/credito-d-imposta-r-s', 'MIMIT - Credito d’imposta R&S, innovazione e design', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Scheda MIMIT sulla misura fiscale R&S.'),
            doc('https://www.agenziaentrate.gov.it/', 'Agenzia Entrate - Riferimenti fiscali credito R&S', DocumentRole.MINISTERIAL_CIRCULAR.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'supporting_document', 'Supporto fiscale e interpretativo della misura.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - riferimenti credito R&S', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Traccia di base normativa e aggiornamenti.'),
        ],
        'requirements': [
            req('digital_transition_project', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('patent_ip_intent', RequirementMode.RANKING_OR_BOOSTER.value, ['true']),
            req('sector_macro_category', RequirementMode.RANKING_OR_BOOSTER.value, ['digitale', 'agritech', 'energia', 'manifattura', 'creative']),
        ],
    },
    {
        'slug': 'voucher_3i',
        'title': 'Voucher 3I',
        'operator_name': 'MIMIT',
        'source_domain': 'mimit.gov.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'voucher',
        'benefit_magnitude_model': 'service_voucher',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup'],
        'size_constraints': ['micro', 'small'],
        'sector_constraints': ['digitale', 'energia', 'agritech', 'manifattura', 'servizi'],
        'legal_form_constraints': ['innovative_startup', 'srl'],
        'regime_status_constraints': ['startup_innovativa', 'not_sure'],
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': ['patent_ip_intent'],
        'application_mechanics': {'channel': 'invitalia_or_partner_portal'},
        'required_documents': ['Documentazione brevetto o consulenza IP'],
        'entrypoint_urls': ['https://www.mimit.gov.it/it/incentivi/voucher-3i-investire-in-innovazione%20'],
        'allowed_path_keywords': ['voucher', '3i', 'innovazione', 'brevetti'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Voucher per servizi di consulenza in materia di proprieta intellettuale e brevettuale.'}],
        'documents': [
            doc('https://www.mimit.gov.it/it/incentivi/voucher-3i-investire-in-innovazione%20', 'MIMIT - Voucher 3I', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Scheda ufficiale del Voucher 3I.'),
            doc('https://www.mimit.gov.it/it/startup-innovative', 'MIMIT - Startup innovative', DocumentRole.IMPLEMENTING_DECREE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'supporting_eligibility_regime', 'Status di startup innovativa spesso rilevante per il Voucher 3I.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - riferimenti Voucher 3I', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Riferimenti regolatori della misura Voucher 3I.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['startup']),
            req('innovation_regime_status', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['startup_innovativa', 'not_sure']),
            req('patent_ip_intent', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
        ],
    },
    {
        'slug': 'simest_fiere_eventi',
        'title': 'SIMEST - Fiere ed eventi',
        'operator_name': 'SIMEST',
        'source_domain': 'simest.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'finanziamento_agevolato',
        'benefit_magnitude_model': 'export_financing',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme'],
        'size_constraints': ['micro', 'small', 'medium'],
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': ['export_investment_intent'],
        'application_mechanics': {'channel': 'simest_portal'},
        'required_documents': ['Piano partecipazione fiera', 'Preventivi spesa', 'Documenti societari'],
        'entrypoint_urls': ['https://www.simest.it/per-le-imprese/finanziamenti-agevolati/finanziamenti-agevolati-internazionalizzazione/fiere-eventi/'],
        'allowed_path_keywords': ['fiere', 'eventi', 'simest'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Finanziamento agevolato per fiere ed eventi internazionali.'}],
        'documents': [
            doc('https://www.simest.it/per-le-imprese/finanziamenti-agevolati/finanziamenti-agevolati-internazionalizzazione/fiere-eventi/', 'SIMEST - Fiere ed eventi', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Scheda operativa SIMEST per fiere ed eventi.'),
            doc('https://www.simest.it/', 'SIMEST - Portale domanda fiere', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'application_channel', 'Portale domanda per la linea fiere ed eventi.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - riferimenti SIMEST fiere', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Base regolatoria e aggiornamenti delle linee SIMEST.'),
        ],
        'requirements': [
            req('export_investment_intent', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('target_market_scope', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['eu', 'extra_eu', 'both', 'not_sure']),
            req('size_band', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['micro', 'small', 'medium']),
        ],
    },
    {
        'slug': 'simest_ecommerce',
        'title': 'SIMEST - E-commerce',
        'operator_name': 'SIMEST',
        'source_domain': 'simest.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'finanziamento_agevolato',
        'benefit_magnitude_model': 'export_financing',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme'],
        'size_constraints': ['micro', 'small', 'medium'],
        'sector_constraints': ['retail', 'digitale', 'manifattura', 'turismo'],
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': ['export_investment_intent', 'digital_transition_project'],
        'application_mechanics': {'channel': 'simest_portal'},
        'required_documents': ['Piano e-commerce estero', 'Preventivi piattaforma', 'Documenti societari'],
        'entrypoint_urls': ['https://www.simest.it/per-le-imprese/finanziamenti-agevolati/finanziamenti-agevolati-internazionalizzazione/ecommerce/'],
        'allowed_path_keywords': ['ecommerce', 'simest', 'internazionalizzazione'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Linea agevolata per sviluppo di canali e-commerce su mercati esteri.'}],
        'documents': [
            doc('https://www.simest.it/per-le-imprese/finanziamenti-agevolati/finanziamenti-agevolati-internazionalizzazione/ecommerce/', 'SIMEST - E-commerce', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Scheda SIMEST per progetti e-commerce estero.'),
            doc('https://www.simest.it/', 'SIMEST - Portale domanda e-commerce', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'application_channel', 'Portale domanda linea e-commerce.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - riferimenti SIMEST e-commerce', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Riferimenti generali della linea SIMEST e-commerce.'),
        ],
        'requirements': [
            req('export_investment_intent', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('digital_transition_project', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('target_market_scope', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['eu', 'extra_eu', 'both', 'not_sure']),
        ],
    },
    {
        'slug': 'simest_inserimento_mercati',
        'title': 'SIMEST - Inserimento mercati esteri',
        'operator_name': 'SIMEST',
        'source_domain': 'simest.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'finanziamento_agevolato',
        'benefit_magnitude_model': 'export_financing',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme'],
        'size_constraints': ['micro', 'small', 'medium'],
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': ['export_investment_intent'],
        'application_mechanics': {'channel': 'simest_portal'},
        'required_documents': ['Piano ingresso mercati', 'Budget sviluppo estero'],
        'entrypoint_urls': ['https://www.simest.it/per-le-imprese/finanziamenti-agevolati/finanziamenti-agevolati-internazionalizzazione/inserimento-sui-mercati-esteri/'],
        'allowed_path_keywords': ['mercati-esteri', 'simest', 'export'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Linea per apertura e presidio di mercati esteri.'}],
        'documents': [
            doc('https://www.simest.it/per-le-imprese/finanziamenti-agevolati/finanziamenti-agevolati-internazionalizzazione/inserimento-sui-mercati-esteri/', 'SIMEST - Inserimento sui mercati esteri', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Scheda SIMEST per inserimento mercati esteri.'),
            doc('https://www.simest.it/', 'SIMEST - Portale domanda inserimento mercati', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'application_channel', 'Portale domanda per inserimento sui mercati esteri.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - riferimenti inserimento mercati', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Riferimenti pubblici della linea SIMEST inserimento mercati.'),
        ],
        'requirements': [
            req('export_investment_intent', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('target_market_scope', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['eu', 'extra_eu', 'both', 'not_sure']),
            req('size_band', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['micro', 'small', 'medium']),
        ],
    },
    {
        'slug': 'simest_transizione_digitale_ecologica',
        'title': 'SIMEST - Transizione digitale o ecologica',
        'operator_name': 'SIMEST',
        'source_domain': 'simest.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.OPEN_APPLICATION.value,
        'benefit_kind': 'finanziamento_agevolato',
        'benefit_magnitude_model': 'export_financing',
        'geography': 'Italy',
        'beneficiary_entity_types': ['startup', 'sme'],
        'size_constraints': ['micro', 'small', 'medium'],
        'sector_constraints': ['digitale', 'energia', 'manifattura', 'servizi'],
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': ['digital_transition_project', 'energy_transition_project'],
        'application_mechanics': {'channel': 'simest_portal'},
        'required_documents': ['Piano trasformazione', 'Budget progetto'],
        'entrypoint_urls': ['https://www.simest.it/per-le-imprese/finanziamenti-agevolati/finanziamenti-agevolati-internazionalizzazione/transizione-digitale-o-ecologica/'],
        'allowed_path_keywords': ['transizione-digitale', 'ecologica', 'simest'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Linea per progetti di transizione digitale o ecologica con impatto sull’internazionalizzazione.'}],
        'documents': [
            doc('https://www.simest.it/per-le-imprese/finanziamenti-agevolati/finanziamenti-agevolati-internazionalizzazione/transizione-digitale-o-ecologica/', 'SIMEST - Transizione digitale o ecologica', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'primary_operational', 'Scheda SIMEST sulla transizione digitale/ecologica.'),
            doc('https://www.simest.it/', 'SIMEST - Portale domanda transizione digitale/ecologica', DocumentRole.APPLICATION_PORTAL.value, MeasureLifecycleStatus.OPEN_APPLICATION.value, 'application_channel', 'Portale domanda per la linea digitale/ecologica.'),
            doc('https://www.gazzettaufficiale.it/', 'Gazzetta Ufficiale - riferimenti transizione SIMEST', DocumentRole.NEWS_OR_STATUS_UPDATE.value, MeasureLifecycleStatus.HISTORICAL_REFERENCE.value, 'publication_trail', 'Riferimenti generali della linea SIMEST transizione.'),
        ],
        'requirements': [
            req('export_investment_intent', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('digital_transition_project', RequirementMode.PROJECT_HARD_REQUIREMENT.value, ['true']),
            req('energy_transition_project', RequirementMode.RANKING_OR_BOOSTER.value, ['true']),
        ],
    },
    {
        'slug': 'assegno_unico_universale',
        'title': 'Assegno Unico Universale',
        'operator_name': 'INPS',
        'source_domain': 'inps.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'direct_transfer',
        'benefit_magnitude_model': 'monthly_allowance',
        'geography': 'Italy',
        'beneficiary_entity_types': ['persona_fisica'],
        'size_constraints': None,
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': ['familia_con_figli'],
        'project_specific_constraints': None,
        'application_mechanics': {'channel': 'inps_online', 'portal': 'inps.it'},
        'required_documents': ['ISEE in corso di validita', 'Documento identita', 'Codice fiscale figli'],
        'entrypoint_urls': ['https://www.inps.it/assegno-unico'],
        'allowed_path_keywords': ['assegno-unico', 'figli', 'famiglie'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Assegno mensile fino a 199,4 euro per figlio sotto i 21 anni, modulato per ISEE.'}],
        'documents': [
            doc('https://www.inps.it/assegno-unico', 'INPS - Assegno Unico Universale', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Pagina operativa INPS con importi, requisiti e modalita di domanda per l\'Assegno Unico Universale.'),
            doc('https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2021-09-29;230', 'D.Lgs. 230/2021 - Assegno Unico', DocumentRole.LEGAL_BASIS.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_legal_basis', 'Decreto istitutivo dell\'Assegno Unico e Universale per i figli a carico.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['persona_fisica']),
            req('family_composition', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['coppia_con_figli', 'genitore_solo_con_figli']),
            req('figli_a_carico_count', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['1', '2', '3_plus']),
            req('isee_bracket', RequirementMode.RANKING_OR_BOOSTER.value, ['under_15k', '15_25k']),
        ],
    },
    {
        'slug': 'bonus_nido_inps',
        'title': 'Contributo Asilo Nido INPS',
        'operator_name': 'INPS',
        'source_domain': 'inps.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'direct_transfer',
        'benefit_magnitude_model': 'annual_reimbursement',
        'geography': 'Italy',
        'beneficiary_entity_types': ['persona_fisica'],
        'size_constraints': None,
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': ['figli_under_3'],
        'project_specific_constraints': None,
        'application_mechanics': {'channel': 'inps_online', 'portal': 'inps.it'},
        'required_documents': ['ISEE minorenni', 'Ricevute pagamento nido', 'Codice fiscale figlio'],
        'entrypoint_urls': ['https://www.inps.it/bonus-asilo-nido'],
        'allowed_path_keywords': ['asilo-nido', 'bonus-nido', 'figli'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Contributo fino a 3.600 euro annui per rette di asilo nido, modulato per ISEE.'}],
        'documents': [
            doc('https://www.inps.it/bonus-asilo-nido', 'INPS - Bonus Asilo Nido', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Scheda operativa INPS con importi per fascia ISEE e procedura di richiesta del bonus nido.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['persona_fisica']),
            req('family_composition', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['coppia_con_figli', 'genitore_solo_con_figli']),
            req('figli_a_carico_count', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['1', '2', '3_plus']),
            req('isee_bracket', RequirementMode.RANKING_OR_BOOSTER.value, ['under_15k']),
        ],
    },
    {
        'slug': 'naspi_disoccupazione',
        'title': 'NASpI — Indennita di Disoccupazione',
        'operator_name': 'INPS',
        'source_domain': 'inps.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'income_replacement',
        'benefit_magnitude_model': 'percentage_of_salary',
        'geography': 'Italy',
        'beneficiary_entity_types': ['persona_fisica'],
        'size_constraints': None,
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': ['ex_dipendente_disoccupato'],
        'project_specific_constraints': None,
        'application_mechanics': {'channel': 'inps_online', 'portal': 'inps.it'},
        'required_documents': ['Dichiarazione di disponibilita al lavoro', 'Documento identita'],
        'entrypoint_urls': ['https://www.inps.it/naspi'],
        'allowed_path_keywords': ['naspi', 'disoccupazione', 'indennita'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Indennita mensile pari al 75% della retribuzione media mensile, per un massimo di 1.352 euro.'}],
        'documents': [
            doc('https://www.inps.it/naspi', 'INPS - NASpI', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Pagina INPS con requisiti, calcolo e procedura di domanda per la NASpI.'),
            doc('https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2015-03-04;22', 'D.Lgs. 22/2015 - NASpI', DocumentRole.LEGAL_BASIS.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_legal_basis', 'Decreto istitutivo della Nuova Assicurazione Sociale per l\'Impiego.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['persona_fisica']),
            req('employment_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['disoccupato']),
        ],
    },
    {
        'slug': 'regime_forfettario_accesso',
        'title': 'Regime Forfettario — Accesso e Agevolazioni',
        'operator_name': 'Agenzia delle Entrate',
        'source_domain': 'agenziaentrate.gov.it',
        'is_regime_only': True,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'tax_regime',
        'benefit_magnitude_model': 'flat_tax_rate',
        'geography': 'Italy',
        'beneficiary_entity_types': ['persona_fisica'],
        'size_constraints': None,
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': ['autonomo_soglia_85k'],
        'project_specific_constraints': None,
        'application_mechanics': {'channel': 'dichiarazione_redditi', 'portal': 'agenziaentrate.gov.it'},
        'required_documents': ['Partita IVA', 'Registro incassi e pagamenti'],
        'entrypoint_urls': ['https://www.agenziaentrate.gov.it/portale/web/guest/schede/agevolazioni/regime-forfetario'],
        'allowed_path_keywords': ['forfetario', 'partita-iva', 'flat-tax', 'agevolazioni'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Imposta sostitutiva del 15% (5% per i primi 5 anni) su ricavi fino a 85.000 euro.'}],
        'documents': [
            doc('https://www.agenziaentrate.gov.it/portale/web/guest/schede/agevolazioni/regime-forfetario', 'Agenzia Entrate - Regime Forfetario', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Scheda operativa con requisiti, coefficienti di redditivita e procedura di accesso al regime forfetario.'),
            doc('https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:2014-12-23;190~art1', 'Legge 190/2014 art.1 - Regime Forfetario', DocumentRole.LEGAL_BASIS.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_legal_basis', 'Norma istitutiva del regime forfetario per lavoro autonomo.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['persona_fisica']),
            req('employment_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['autonomo']),
            req('persona_fisica_age_band', RequirementMode.RANKING_OR_BOOSTER.value, ['under_35']),
        ],
    },
    {
        'slug': 'adi_assegno_inclusione',
        'title': 'ADI — Assegno di Inclusione',
        'operator_name': 'INPS',
        'source_domain': 'inps.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'direct_transfer',
        'benefit_magnitude_model': 'monthly_allowance',
        'geography': 'Italy',
        'beneficiary_entity_types': ['persona_fisica'],
        'size_constraints': None,
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': ['family_with_minors_or_disabled_or_over60'],
        'project_specific_constraints': None,
        'application_mechanics': {'channel': 'inps_online', 'portal': 'inps.it'},
        'required_documents': ['ISEE in corso di validita', 'Documento identita', 'DSU aggiornata'],
        'entrypoint_urls': ['https://www.inps.it/assegno-inclusione'],
        'allowed_path_keywords': ['assegno-inclusione', 'adi', 'poverta', 'inclusione'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Sussidio mensile fino a 780 euro per famiglie con ISEE sotto 9.360 euro con minori, disabili o over 60.'}],
        'documents': [
            doc('https://www.inps.it/assegno-inclusione', 'INPS - Assegno di Inclusione', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Pagina operativa INPS con requisiti, importi e procedura di domanda per ADI.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['persona_fisica']),
            req('family_composition', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['coppia_con_figli', 'genitore_solo_con_figli']),
            req('isee_bracket', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['under_15k']),
        ],
    },
    {
        'slug': 'detrazioni_mediche_730',
        'title': 'Detrazioni Spese Mediche 730',
        'operator_name': 'Agenzia delle Entrate',
        'source_domain': 'agenziaentrate.gov.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'tax_deduction',
        'benefit_magnitude_model': 'percentage_deduction',
        'geography': 'Italy',
        'beneficiary_entity_types': ['persona_fisica'],
        'size_constraints': None,
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': None,
        'application_mechanics': {'channel': 'dichiarazione_redditi', 'portal': 'agenziaentrate.gov.it'},
        'required_documents': ['Scontrini farmacia', 'Ricevute visite mediche', 'Fatture spese sanitarie'],
        'entrypoint_urls': ['https://www.agenziaentrate.gov.it/portale/web/guest/schede/dichiarazioni/spese-sanitarie'],
        'allowed_path_keywords': ['spese-sanitarie', 'detrazioni', '730', 'salute'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Detrazione IRPEF del 19% su spese mediche e sanitarie con franchigia di 129 euro.'}],
        'documents': [
            doc('https://www.agenziaentrate.gov.it/portale/web/guest/schede/dichiarazioni/spese-sanitarie', 'Agenzia Entrate - Spese sanitarie detraibili', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Guida completa alle spese sanitarie detraibili nel 730.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['persona_fisica']),
        ],
    },
    {
        'slug': 'ecobonus_riqualificazione_energetica',
        'title': 'Ecobonus — Riqualificazione Energetica 65%',
        'operator_name': 'Agenzia delle Entrate / ENEA',
        'source_domain': 'agenziaentrate.gov.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'tax_deduction',
        'benefit_magnitude_model': 'percentage_deduction',
        'geography': 'Italy',
        'beneficiary_entity_types': ['persona_fisica'],
        'size_constraints': None,
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': None,
        'project_specific_constraints': ['energy_efficiency_intervention'],
        'application_mechanics': {'channel': 'dichiarazione_redditi', 'asseverazione': 'ENEA'},
        'required_documents': ['Fatture lavori', 'Bonifico parlante', 'Asseverazione energetica', 'Comunicazione ENEA'],
        'entrypoint_urls': ['https://www.agenziaentrate.gov.it/portale/web/guest/schede/agevolazioni/riqualificazione-energetica'],
        'allowed_path_keywords': ['ecobonus', 'riqualificazione-energetica', 'risparmio-energetico'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Detrazione IRPEF 65% su lavori di risparmio energetico: caldaie, coibentazione, infissi.'}],
        'documents': [
            doc('https://www.agenziaentrate.gov.it/portale/web/guest/schede/agevolazioni/riqualificazione-energetica', 'Agenzia Entrate - Ecobonus', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Guida operativa alle detrazioni per riqualificazione energetica degli edifici.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['persona_fisica']),
            req('home_ownership_status', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['proprietario', 'inquilino_contratto_registrato']),
            req('energy_transition_project', RequirementMode.RANKING_OR_BOOSTER.value, ['true']),
        ],
    },
    {
        'slug': 'legge_104_agevolazioni',
        'title': 'Legge 104 — Agevolazioni e Permessi',
        'operator_name': 'INPS',
        'source_domain': 'inps.it',
        'is_regime_only': False,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'mixed_benefit',
        'benefit_magnitude_model': 'allowance_plus_deduction',
        'geography': 'Italy',
        'beneficiary_entity_types': ['persona_fisica'],
        'size_constraints': None,
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': ['disabilita_certificata'],
        'project_specific_constraints': None,
        'application_mechanics': {'channel': 'inps_online', 'portal': 'inps.it'},
        'required_documents': ['Verbale INPS disabilita', 'Documento identita'],
        'entrypoint_urls': ['https://www.inps.it/legge-104'],
        'allowed_path_keywords': ['legge-104', 'disabilita', 'permessi', 'handicap'],
        'evidence_snippets': [{'field': 'benefit', 'quote': '3 giorni di permesso retribuito mensile per assistenza familiare con disabilita grave.'}],
        'documents': [
            doc('https://www.inps.it/legge-104', 'INPS - Legge 104', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Guida INPS ai permessi e alle agevolazioni previste dalla Legge 104/92.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['persona_fisica']),
            req('disability_status', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['legge_104_in_famiglia', 'invalidita_civile', 'indennita_accompagnamento']),
        ],
    },
    {
        'slug': 'rientro_cervelli_impatriati',
        'title': "Rientro Cervelli — Regime Impatriati",
        'operator_name': 'Agenzia delle Entrate',
        'source_domain': 'agenziaentrate.gov.it',
        'is_regime_only': True,
        'is_actionable': True,
        'current_lifecycle_status': MeasureLifecycleStatus.EVERGREEN_REGIME.value,
        'benefit_kind': 'tax_regime',
        'benefit_magnitude_model': 'income_exemption',
        'geography': 'Italy',
        'beneficiary_entity_types': ['persona_fisica', 'freelancer'],
        'size_constraints': None,
        'sector_constraints': None,
        'legal_form_constraints': None,
        'regime_status_constraints': None,
        'age_or_time_constraints': None,
        'person_specific_constraints': ['rientro_da_estero'],
        'project_specific_constraints': None,
        'application_mechanics': {'channel': 'dichiarazione_redditi', 'portal': 'agenziaentrate.gov.it'},
        'required_documents': ['Prova residenza estera', 'Codice fiscale', 'Contratto di lavoro o P.IVA'],
        'entrypoint_urls': ['https://www.agenziaentrate.gov.it/portale/regime-impatriati'],
        'allowed_path_keywords': ['impatriati', 'rientro', 'cervelli', 'agevolazione'],
        'evidence_snippets': [{'field': 'benefit', 'quote': 'Esenzione del 50% del reddito per 5 anni (90% per il Sud o con figli) per chi trasferisce la residenza in Italia.'}],
        'documents': [
            doc('https://www.agenziaentrate.gov.it/portale/regime-impatriati', 'Agenzia Entrate - Regime Impatriati', DocumentRole.OPERATOR_MEASURE_PAGE.value, MeasureLifecycleStatus.EVERGREEN_REGIME.value, 'primary_operational', 'Scheda operativa del regime agevolato per lavoratori impatriati.'),
        ],
        'requirements': [
            req('profile_type', RequirementMode.ENTITY_HARD_REQUIREMENT.value, ['persona_fisica', 'freelancer']),
        ],
    },
]
